language: node_js
node_js:
    - "7"

dist: trusty

sudo: required

install:
    - sudo apt-get -y install libgif-dev calibre npm
    - sudo npm config set strict-ssl false
    - sudo npm cache clean -f
    - sudo npm install -g n
    - sudo n stable
    - sudo ln -sf /usr/local/n/versions/node/8.0.0/bin/node /usr/bin/node
    - sudo npm update -g
    - npm install gitbook-cli -g
    - npm install gitbook-plugin-autocover
    - npm install gitbook-plugin-github
    - npm install gitbook-plugin-toc
    - npm install gitbook-plugin-anchors
    - npm install gitbook-plugin-image-class

script:
    - gitbook install
    - gitbook build
