language: node_js
node_js:
    - "14"

dist: trusty

sudo: required

install:
    - sudo apt-get -y install libgif-dev calibre npm
    - sudo npm config set strict-ssl false
    - sudo npm cache clean -f
    - sudo npm install -g n
    - sudo n stable
    - sudo npm update -g
    - npm install honkit
    - npm install gitbook-plugin-github
    - npm install gitbook-plugin-toc
    - npm install gitbook-plugin-anchors
    - npm install gitbook-plugin-image-class
    - npm install gitbook-plugin-codesnippet
    - npm install gitbook-plugin-last-modified
    - npm install gitbook-plugin-sitemap

script:
    - npm install honkit
    - npx honkit build
