language: node_js

dist: trusty

sudo: required

install:
    - sudo apt-get -y install libgif-dev calibre
    - npm install -g n
    - n stable
    - npm install gitbook-cli -g
    - npm install gitbook-plugin-autocover
    - npm install gitbook-plugin-github
    - npm install gitbook-plugin-toc
    - npm install gitbook-plugin-anchors

script:
    - gitbook install
    - gitbook build
